### ISSUE TITLE
Player Labels Glitching

### ISSUE THREAD

**Issue by chloe684** [neu-se/covey.town#107]
My group and I noticed that when we enter a Covey.town, the labels start glitching. We'll have multiple tabs open, one for each Player in a same Town, and when we move one Player, the labels will appear delayed in other tabs or won't appear at all. We originally thought this might be due to our implementing a Teleport functionality, but we realized this glitch was also happening on our main branch, were we haven't pushed any teleport functionality. After a discussion with our TA, where he confirmed that the glitch was happening in this repo as well, he suggested we report the issue here.

**Comment by jon-bell** [comment]
Would you please provide more information about how to to reproduce this bug on https://app.covey.town ? I am unable to reproduce it, please see [my screen recording](https://user-images.githubusercontent.com/2130186/204331443-722d01bf-2e39-4cbf-ae44-a11c148ee453.mov).



@shashwatrathod - could you chime in with more information on your steps to reproduce this, as well? Thanks.

**Comment by shashwatrathod** [comment]
Hi,
This is how I was able to reproduce this bug:
1. Enter a town as `player1`. Do not move this player.
2. Enter the same town as `player2`.
3. Make `player2` move. You will notice that `player1` can't see `player2`'s label at all.
4. Make `player1` move. You will notice that for `player2`, while `player1` has moved their label still stays at the previous location.

Attaching a [screen capture](https://user-images.githubusercontent.com/42975283/204346876-34a2690a-c410-4026-9bc9-8012dde25eb4.mp4) for your reference.
