### ISSUE TITLE
conversation areas naming bug

### ISSUE THREAD

**Issue by MihirManek** [neu-se/covey.town#91]
Consider a scenario wherein a user decides to name a conversation area first after entering it. 

1. User presses `Space` which opens up the popup to enter the Topic of the conversation for the current area.
2. User does not enter any topic in the popup and clicks `Cancel`.
3. After canceling, 
> **_Expected behavior_** - The user should be able to move freely across the map.
> **_Actual behavior_** - The user is not able to move their character.

Only after the user enters a topic in the popup is the character allowed to move.

**Comment by jon-bell** [comment]
Thanks for the find! Fixed in e81aab3 and deployed on app.covey.town and staging.covey.town.
